# file: cassandra/tasks/main.yml

- include: source.yml
  when: cassandra_install_method == "source"
  tags:
    - cassandra
- include: package.yml
  when: cassandra_install_method == "package"
  tags:
    - cassandra
#- include: opscenter.yml
#  tags:
#    - cassandra
#    - opscenter
#- include: logstash.yml
#  tags:
#    - cassandra
#    - logstash
