- name: Make sure the opscenter user directory exists
  file:
    path: "{{opscenter_user_dir}}"
    state: directory

- name: Make sure the opscenter user is present
  user:
    name: "{{opscenter_user}}"
    uid: "{{opscenter_uid}}"
    group: "{{cassandra_group}}"
    comment: "Opscenter user"
    home: "{{opscenter_user_dir}}"
    shell: /bin/bash
    state: present

- name: Create the opscenter user .ssh directory
  file: path="{{ opscenter_user_dir }}/.ssh" state=directory owner={{ opscenter_user }} group={{ cassandra_group }} mode=0700

- name: Create the opscenter user SSH private key
  copy: src="opscenter_user_ssh_key" dest="{{ opscenter_user_dir }}/.ssh/id_rsa" owner={{ opscenter_user }} group={{ cassandra_group }} mode=0600

- name: Create the opscenter user SSH public key
  copy: src="opscenter_user_ssh_key.pub" dest="{{ opscenter_user_dir }}/.ssh/id_rsa.pub" owner={{ opscenter_user }} group={{ cassandra_group }} mode=0644

- name: Create the opscenter user SSH .authorized_keys file
  copy: src="opscenter_user_ssh_key.pub" dest="{{ opscenter_user_dir }}/.ssh/authorized_keys" owner={{ opscenter_user }} group={{ cassandra_group }} mode=0644

- name: Install opscenter dependencies
  apt:
    pkg: 'libssl0.9.8'
    state: present

- name: Install opscenter
  apt:
    pkg: "{{ opscenter_package }}"
    state: present

- name: Update the opscenter configuration
  template:
    src: "{{item}}.j2"
    dest: "/etc/opscenter/{{item}}"
    owner: "{{opscenter_user}}"
    group: "{{cassandra_group}}"
    mode: 0644
  with_items:
    - "opscenterd.conf"
  notify:
    - restart opscenterd

- name: Start opscenterd
  service: name=opscenterd state={{opscenter_state}} enabled={{ opscenter_enable }}

- file: state="directory" path="{{ opscenter_log_dir}}" owner="{{ opscenter_user }}" group="{{ cassandra_group }}" recurse="yes"
  notify:
    - restart opscenterd
- file: state="directory" path="{{ opscenter_etc_dir}}" owner="{{ opscenter_user }}" group="{{ cassandra_group }}" recurse="yes"
  notify:
    - restart opscenterd

- name: Install datastax-agent
  apt:
    pkg: datastax-agent
    state: present
- name: start datastax-agent
  service: name="datastax-agent" enabled=true
- name: Update datastax config
  template:
    src: "datastax-agent-conf-address.yaml.j2"
    dest: "/var/lib/datastax-agent/conf/address.yaml"
  notify:
    - restart datastax-agent
